name: Container Build
on:
  push:
    branches:
      - main
  pull_request_target:

jobs:
  container_build:
    name: Container Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Yarn Tasks
        run: |
          yarn && yarn tsc && yarn build

      - name: Create container
        run: yarn build-image

      - name: Upload Container
        run: |
          docker login --username=_ --password=$(heroku auth:token) registry.heroku.com \
          docker tag backstage:latest registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web \
          docker push registery.heroku.com/${{ env.HEROKU_APP_NAME }}/web
