name: Container Build
on:
  push:
    branches:
      - main
  pull_request_target:

jobs:
  container_build:
    name: Container Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Heroku Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: "_"
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Yarn Tasks
        run: |
          yarn && yarn tsc && yarn build

      - name: Create container
        run: yarn build-image --tag registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web


      - name: Upload Container
        run: |
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
